In [13]:
import numpy as np
for i in range(1,7):
    k=np.array([0.0,0.0,0.0,0.0,0.0])
    if(i==1):
        pass
    else:
        k[i-2]=1.0
        print(k)

[1. 0. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 0. 1. 0. 0.]
[0. 0. 0. 1. 0.]
[0. 0. 0. 0. 1.]


In [14]:
type(k)

numpy.ndarray

In [15]:
k=np.append(k,[3.0,1.9,2.0,2.123,3.5,4.6,3.45,6.2543,2.34])

In [16]:
print(k)

[0.     0.     0.     0.     1.     3.     1.9    2.     2.123  3.5
 4.6    3.45   6.2543 2.34  ]


In [6]:
k

array([0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00,
       3.0000e+00, 1.0000e+00, 2.0000e+00, 2.1230e+03, 3.5000e+01,
       4.6000e+01, 3.4500e+02, 6.2543e+04, 2.3400e+02])